[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
tokio.workspace = true
serde.workspace = true
bytes = "1.11.1"
futures = "0.3.32"
tokio-util = { version = "0.7.18", features = ["codec"] }
ratatui = "0.26"
crossterm = { version = "0.27", features = ["events"] }
